### ISSUE TITLE
Hi，机器人不能用了

### ISSUE THREAD

**Issue by leochan2017** [spacelan/ticker#1]
你好，很高兴搜索到你的项目。

但是，我clone下来测试了下。现在是不能用的。

最后更新代码是5个月前。

请问作者还会继续更新么？

**Comment by spacelan** [comment]
微信最近几个月大力封禁机器人，所以暂时也没有维护了

**Comment by spacelan** [comment]
另外不能用是指的不能登录机器人还是不能够获取报价了？

**Comment by leochan2017** [comment]
不能获取报价呀，搜索下有一个叫“非小号”，和火币的一个机器人还能用。就是贼烦有很长的尾巴。所以想自己部署一个
